[colors.primary]
foreground = '#383a42'
background = '#fafafa'

[colors.cursor]
cursor = '#4078f2'
text   = '#fafafa'

[colors.normal]
black   = '#fafafa'
red     = '#e45649'
green   = '#50a14f'
yellow  = '#986801'
blue    = '#4078f2'
magenta = '#b751b6'
cyan    = '#0184bc'
white   = '#383a42'

[colors.bright]
black   = '#9ca0a4'
red     = '#e45649'
green   = '#50a14f'
yellow  = '#da8548'
blue    = '#4078f2'
magenta = '#b751b6'
cyan    = '#0184bc'
white   = '#efefef'
